### ISSUE TITLE
Align with WINGS Workflow Ontologies

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/sweet#100]
I am using WINGS as a semantic workflow manager for my ongoing side project [COAL](https://capstone-coal.github.io).
I would like to align the WINGS ontologies with SWEET with the aim of being able to link workflow processing to actual semantics of data products being processed.
        
        data = http://www.wings-workflows.org/ontology/data.owl;
        component = http://www.wings-workflows.org/ontology/component.owl;
        workflow = http://www.wings-workflows.org/ontology/workflow.owl;
        execution = http://www.wings-workflows.org/ontology/execution.owl;
        resource = http://www.wings-workflows.org/ontology/resource.owl;

**Comment by charlesvardeman** [comment]
It may also be useful to add alignments to the common workflow language https://www.commonwl.org/
in addition to WINGS since it is more general.
