### ISSUE TITLE
Correct semantics of "Calf"

### ISSUE THREAD

**Issue by pbuttigieg** [ESIPFed/sweet#102]
Hi SWEET team,

We're at a cryosemantics hackathon at ESIP Winter 2019, and have spotted the following error:
https://github.com/ESIPFed/sweet/blob/master/src/realmCryo.ttl#L63-L65

Here, a "calf" is asserted to be a kind of "sea ice". However, as sea ice is frozen out of sea water and calved ice can fall from other ice masses, this isn't so. 

ENVO's next release will clarify some of these semantics in detail:
http://purl.obolibrary.org/obo/ENVO_01001506 (not live yet)

@rduerr

**Comment by pbuttigieg** [comment]
@smrgeoinfo also noted the problematic nature of the label [here](https://github.com/ESIPFed/sweet/pull/190/files#r417748207)

**Comment by rduerr** [comment]
Per the GCW the synonym "Calved ice" probably should be used here.

**Comment by rduerr** [comment]
The term at least should be moved to a parent up a level to somaw:Ice (http://sweetontology.net/matrWater/Ice).  Will change the label to be "ice calf".

**Comment by brandonnodnarb** [comment]
addressed in #286
