### ISSUE TITLE
remove http://org.semanticweb.owlapi/error#Error(n) links

### ISSUE THREAD

**Issue by brandonnodnarb** [ESIPFed/sweet#122]
This is related to the current discussion around the apparent failure of Protege to load SWEET via a URL, relevant thread here: https://lists.esipfed.org/pipermail/esip-semanticweb/2019/001464.html.

After doing more digging I found the error URIs are not derived from the inability of Protege or TopBraid to parse a file or follow a link, the are **in the turtle file**.  For illustration, lines 186-189 of [reprMathOperation.ttl](https://github.com/ESIPFed/sweet/blob/master/src/reprMathOperation.ttl) are:
`oper:IndefiniteIntegral rdf:type owl:Class ;
                        rdfs:subClassOf <http://org.semanticweb.owlapi/error#Error16> ,
                                        oper:Integral ;
                        rdfs:label "indefinite integral"@en .`

Well, that's obviously not correct.  Looking at [the diff of this file from the last pull request (ISSUE-20)](https://github.com/ESIPFed/sweet/commit/15dc96fd70b537de925e3a17831a829f79351cf0#diff-a56cf742c3f33669cfd01965e1b9dc01), it was previously (from line 109):
`oper:IndefiniteIntegral rdf:type owl:Class ;
                        rdfs:subClassOf oper:Integral ,
                                        [ rdf:type owl:Restriction ;
                                          owl:onProperty mrela:hasInterval ;
                                          owl:cardinality "0"^^xsd:nonNegativeInteger
                                        ] .`

The affected files --- i.e. files with 'http://org.semanticweb.owlapi/error#Error[1-9].' within --- are:
reprDataServiceGeospatial.ttl
reprMath.ttl
reprMathFunctionOrthogonal.ttl
reprMathOperation.ttl
reprMathGraph.ttl
 
At present, I do not know how this could hvae happened.  I will fix it.

**Comment by brandonnodnarb** [comment]
the following classes were edited in reprMathOperation.ttl:
1. [oper:DefiniteIntegral](http://sweetontology.net/reprMathOperation/DefiniteIntegral)
2. [oper:IndefiniteIntegral](http://sweetontology.net/reprMathOperation/IndefiniteIntegral)
3. [oper:Integral](http://sweetontology.net/reprMathOperation/Integral)

All were missing their cardinality resrtictions.

**Comment by brandonnodnarb** [comment]
The sole class edited in reprDataServiceGeospatial.ttl was [geos:GeospatialService](http://sweetontology.net/reprDataServiceGeospatial/GeospatialService).   It was missing a cardinality restriction.

**Comment by brandonnodnarb** [comment]
The following classes were edited in reprMath.ttl:
1. [math:OrderedPair](http://sweetontology.net/reprMath/OrderedPair)
2. [math:OrderedTriple](http://sweetontology.net/reprMath/OrderedTriple)

All were missing their cardinality resrtictions.

**Comment by brandonnodnarb** [comment]
The sole class edited in reprMathFunctionOrthogonal.ttl was [orth:SphericalHarmonic](http://sweetontology.net/reprMathFunctionOrthogonal/SphericalHarmonic).  It was missing a cardinality restriction.

**Comment by brandonnodnarb** [comment]
The following classes were edited in reprMathGraph.ttl:
1. [graph:Arc](http://sweetontology.net/reprMathGraph/Arc)
2. [graph:DirectedGraph]( http://sweetontology.net/reprMathGraph/DirectedGraph)
3. [graph:Edge](http://sweetontology.net/reprMathGraph/Edge)
4. [graph:Graph](http://sweetontology.net/reprMathGraph/Graph)
5. [graph:Network](http://sweetontology.net/reprMathGraph/Network)
6. [graph:WeightedEdge](http://sweetontology.net/reprMathGraph/WeightedEdge)

All were missing their cardinality resrtictions.

**Comment by brandonnodnarb** [comment]
Does this relate to #84?  It's an impressively similar error.

**Comment by lewismc** [comment]
Yep it absolutely is. I feel that it is the owlapi version. Possibly between it using OWL 1/OWL2 DL to interpret the input ontology.

**Comment by brandonnodnarb** [comment]
Addressed and merged as part of #123

**Comment by brandonnodnarb** [comment]
Testing resultes: Web import appears to be working fine on TopBraid Composer 5.3 (paid) and 6.1 (free edition) --- i.e. no errors (other than a rando null pointer exception).   However, I'm still getting http 403 errors in Protege 5.5.

Although prematurely marked this a closed before testing, it does seem clear there is at least one issue with using Protege in this manner (loading via URL --- loading from local seems to be fine).

**Comment by lewismc** [comment]
@brandonnodnarb excellent. I can replicate your above results using Protege as well. Good job.
