### ISSUE TITLE
Pyroxene misspelled

### ISSUE THREAD

**Issue by adamancer** [ESIPFed/sweet#128]
Pyroxene is spelled incorrectly in http://cor.esipfed.org/ont?iri=http://sweetontology.net/matrMineral/Pyroxine. The correct spelling is pyroxene, not pyroxine.

## Attribution

0000-0002-7512-4206

**Comment by lewismc** [comment]
I suggest we use ```owl:DeprecatedClass``` to deprecate http://sweetontology.net/matrMineral/Pyroxine and then simply remove it further down the line

**Comment by lewismc** [comment]
Also @adamancer are you able to produce a definition?

**Comment by lewismc** [comment]
According tohttps://www.w3.org/2007/OWL/draft/owl2-quick-reference/#Additional_Vocabulary_in_OWL_2_RDF_Syntax the correct mechanism for deprecating Class is to use the following
```
alternative RDF syntax:
s rdf:type owl:DeprecatedClass . or
s rdf:type owl:DeprecatedProperty .
can be replaced by

s owl:deprecated "true"^^xsd:boolean . 
```

**Comment by dr-shorthair** [comment]
The final version is here: https://www.w3.org/TR/owl2-quick-reference/#Annotations 
https://www.w3.org/TR/owl2-quick-reference/#Additional_Vocabulary_in_OWL_2_RDF_Syntax

**Comment by lewismc** [comment]
@dr-shorthair any recommendations on encoding a "introduced in version XYZ" axiom?

**Comment by smrgeoinfo** [comment]
how about owl:versionInfo -- "annotation property can be used to provide an IRI with a string that describes the IRI's version.  "  This is all there is in the v2 recommendation.
from[ owl 1 recommendation](https://www.w3.org/TR/owl-ref/#versionInfo-def): "Although this property is typically used to make statements about ontologies, it may be applied to any OWL construct. For example, one could attach a owl:versionInfo statement to an OWL class."

**Comment by smrgeoinfo** [comment]
definitions:


[Wikipedia: pyroxene group ('pyroxenes') ](https://en.wikipedia.org/wiki/Pyroxene)"a group of important rock-forming inosilicate minerals found in many igneous and metamorphic rocks. Pyroxenes have the general formula XY(Si,Al)2O6, where X represents calcium, sodium, iron (II) or magnesium and more rarely zinc, manganese or lithium, and Y represents ions of smaller size, such as chromium, aluminum, iron (III), magnesium, cobalt, manganese, scandium, titanium, vanadium or even iron (II). Although aluminum substitutes extensively for silicon in silicates such as feldspars and amphiboles, the substitution occurs only to a limited extent in most pyroxenes. They share a common structure consisting of single chains of silica tetrahedra. Pyroxenes that crystallize in the monoclinic system are known as clinopyroxenes and those that crystallize in the orthorhombic system are known as orthopyroxenes."

**Comment by lewismc** [comment]
Thanks @smrgeoinfo

**Comment by dr-shorthair** [comment]
> @dr-shorthair any recommendations on encoding a "introduced in version XYZ" axiom?

Not quite in that formulation. But 
```
<> prov:wasGeneratedBy [ 
               a prov:Activity ; 
               dct:description "SWEET release XYZ" ; 
      ] . 
```
might work.

**Comment by graybeal** [comment]
I wonder about the value of manually generating update provenance (which will be time-consuming and likely inconsistent) when the exact information about what was updated can be computed from GitHub or COR revision information (and in the future, might be computed in a way that's far more useful). Plus, you don't know what the 'next release' will be, it might unexpectedly be a more minor release.

**Comment by lewismc** [comment]
OK, it was just a thought. I don't think it will be terribly useful to go to too much bother trying to implement this... so for the time being I'm personally not going to pursue that portion any further. Thank you all for the suggestions.

**Comment by brandonnodnarb** [comment]
Given the current modularity, it may be beneficial to have a `depricated.ttl`file for these particular changes.

**Comment by lewismc** [comment]
Merged into master via https://github.com/ESIPFed/sweet/pull/146
