### ISSUE TITLE
Generic Sample

### ISSUE THREAD

**Issue by dr-shorthair** [ESIPFed/sweet#138]
## Preferred term label

Sample

## Textual definition

Material entity, or subset or population, which has been obtained or designed to be representative of a larger entity or universe, usually for the purpose of making observations whose intention is to characterize the larger entity or universe ('feature of interest'). 

Some of its sub-classes are sometimes referred to as material-specimen and statistical-sample.  

Result of an act of sampling (#139)

Has a defining property `isSampleOf` which links to the larger entity or universe. 

An individual sample might not sample the ultimate feature of interest directly, but might rather sample an intermediate sample, so that the relationship to the ultimate feature of interest is through a chain of samples generated by a sequence of acts of sampling. 

See https://www.w3.org/TR/vocab-ssn/#SOSASample 

## Suggested parent term

Likely belongs in reprSciModel module, `mod:Sample`

## Attribution

https://orcid.org/0000-0002-3884-3420

**Comment by dr-shorthair** [comment]
See #107 and #127

**Comment by kaiiam** [comment]
Currently the BCO:[specimen collection process](http://purl.obolibrary.org/obo/OBI_0000659) has axioms:

```
has_specified_input some material entity
has_specified_output some specimen
```

@dr-shorthair am I correct in understanding that this would be intended to describe some sort of ``sample collection process``, which would instead of having the axiom ``has_specified_input some material entity`` instead be something like ``has_specified_input some `` IAO[information content entity]?

**Comment by dr-shorthair** [comment]
The naked term 'sample' is used in some communities to denote 'material sample'. 

The term 'specimen' is used in some communities for 'material sample'.

The term 'specimen' is used in the collections community only to refer to a _curated_ material thing. 

The term 'sample' here relates to the thing's role as a 'sample of' some larger thing, in the context of a thing-characterization-activity.

**Comment by dr-shorthair** [comment]
https://github.com/ESIPFed/sweet/blob/master/src/reprSciModel.ttl#L166 has generic sample concept.
