### ISSUE TITLE
Where is the term, Data, in SWEET?

### ISSUE THREAD

**Issue by rdowns** [ESIPFed/sweet#140]
Under HumanResearch, Result was mentioned as well as other terms that might be produced by research conducted by humans, but the term, Data, did not appear to be present.

## Attribution

If you would like a nanoattribution, please indicate your ORCID id
0000-0002-8595-5134

**Comment by lewismc** [comment]
Here it is Bob
https://github.com/ESIPFed/sweet/blob/4a5378cb048b6f493cfe57fdb85cf4c90f30baa4/src/reprDataProduct.ttl#L72-L75
