### ISSUE TITLE
double check state files on prefix.cc

### ISSUE THREAD

**Issue by brandonnodnarb** [ESIPFed/sweet#161]
related to #155 
TL;DR --- verify all state URIs have been registered properly.

I didn't realise at the time, but when adding the .../state{...} prefixes and URIs to prefix.cc there were a few (three, from memory) that were already listed.  These were SWEET URIs so I assumed someone had already added them and I missed the email.   However, need to verify these are not internal NS collisions.

**Comment by lewismc** [comment]
Hi @brandonnodnarb I manually checked each and every one... they are all good. Thanks for registering this and smashing this issue.
