### ISSUE TITLE
fix URI typo in SHACL file as well as on prefix.cc

### ISSUE THREAD

**Issue by brandonnodnarb** [ESIPFed/sweet#166]
In checking the PR for #165, I've notice conflicting URIs.   
In the ttl file for [phenAtmoWindMesoscale](https://github.com/ESIPFed/sweet/blob/master/src/phenAtmoWindMesoscale.ttl) the URI is https://sweetontology.net/phenAtmoWindMesoscale.ttl

However, in the SHACL file and on prefix.cc the URI is http://sweetontology.net/phenAtmoWindMesostcale/  (note the 't' in scale)

I assume all the URIs in the SWEET files are sans the errant 't'.  A quick spot check seems to verify this.  Easiest resolution seems be to fix the SHACL typo and add the correct URI to prefix.cc and then have everyone go "upvote" the correct URI.  (Rather than changing the URIs in every SWEET ttl file.) 

I'm happy to go ahead, but thought I'd log an issue incase I've missed something obvious.  (It's been that kind of week.)

**Comment by lewismc** [comment]
Good catch @brandonnodnarb what a PITA but the good thing is that it shows peer review is working... eventually :)
If you can go ahead and register the new entry in prefix.cc and then create the PR that would be great.

**Comment by brandonnodnarb** [comment]
addressed with PR #167 

please also go to:
http://prefix.cc/sophatmowm
and upvote the corrected URI (the one without the 't' in mesoscale)

**Comment by lewismc** [comment]
DONE :)

**Comment by brandonnodnarb** [comment]
merged
