### ISSUE TITLE
Database Cross Reference

### ISSUE THREAD

**Issue by charlesvardeman** [ESIPFed/sweet#179]
During the SWEET-ENVO Cryosphere harmonization "Vocamps", database cross-references were captured in ENVO using the [database_cross_reference](https://github.com/EnvironmentOntology/envo/wiki/Adding-classes-to-ENVO#nano-crediting) pointing to the SWEET URI for the term. The reciprocal relation was not captured in SWEET because no mechanism currently exists. ENVO utilizes the <http://www.geneontology.org/formats/oboInOwl#hasDbXref > annotation property for capturing this information that is contained in the [OBO Format metamodel](https://www.bioontology.org/wiki/OboInOwl:Main_Page). During the [AGU Community Ontology Engineering Workshop](https://www.agu.org/Events/SCIWS2-Geoscience-Community-Ontology-Engineering) several options were discussed to add the ability for cross-references in SWEET.

1) Directly reference the <http://www.geneontology.org/formats/oboInOwl#> prefix in SWEET and use hasDbXref annotation property.
2) Create a new class in SWEET that is essentially the  equivalent to:
```
:DbXref a owl:Class ;
:hasDbXref a owl:AnnotationProperty .
:hasURI a owl:AnnotationProperty .
```

Where the :hasDbXref property takes the "http://www.w3.org/2001/XMLSchema#anyURI datatype".  No obvious consensus was reached during the workshop as to where this class and property should be located in the SWEET hierarchy. It was discussed that a potential solution would be to create a utility module to contain these classes which would have the advantage of being extensible if other relations from oboInOwl need to be utilized (ex  #replacedBy, #consider, etc).

**Comment by cmungall** [comment]
I recommend using skos

I think we should also include skos in the ENVO release. We use dbxref for historic reasons. See

https://douroucouli.wordpress.com/2019/05/27/never-mind-the-logix-taming-the-semantic-anarchy-of-mappings-in-ontologie/

**Comment by cmungall** [comment]
To be clear on the workflow:

the master location will be in ENVO, all edits will be made there, and as part of the sweet release process or as a periodic step there will be some kind of SPARQL UPDATE or similar to update SWEET?

**Comment by lewismc** [comment]
@charlesvardeman given the conversation we had yesterday can we close this issue off? Can you please provide your input before closing off? Thanks

**Comment by pbuttigieg** [comment]
Xref #126

**Comment by charlesvardeman** [comment]
So, in talking this past week during the harmonization cluster I think for now we want to manually do the cross-mapping using SKOS as we are doing the harmonization effort. I have made some progress on the realmCryo and we will sanity check it during a Harmonization Cluster hackathon at the beginning of Feb.  I will do a pull request on the updated realmCryo after the sanity check. We think about automated methods to update SWEET by pulling from ENVO after the realmCryo is sorted.

**Comment by lewismc** [comment]
@charlesvardeman is this issue still relevant? It looks like the semantic harmonization group agreed NOT to use `hasDbXref`. Is this correct?

**Comment by charlesvardeman** [comment]
I can close this issue. We now are using skos as an explicit xref, with more formal alignment using owl once some of the underlying structure of the semantics of SWEET is resolved.
