### ISSUE TITLE
Publish SWEET as Linked Data

### ISSUE THREAD

**Issue by dr-shorthair** [ESIPFed/sweet#18]
SWEET is currently published only in OWL/XML format. 
Most non-Protege users prefer Turtle or JSON-LD. 

Ideally SWEET should be provided in various serializations, through HTTP content negotiation.

**Comment by graybeal** [comment]
Um, I think it is provided in multiple serializations, on both ESIP platforms. Am I missing something?

john

On Jul 24, 2017, at 7:30 PM, Simon Cox <notifications@github.com<mailto:notifications@github.com>> wrote:


SWEET is currently published only in OWL/XML format.
Most non-Protege users prefer Turtle or JSON-LD.

Ideally SWEET should be provided in various serializations, through HTTP content negotiation.

**Comment by dr-shorthair** [comment]
Maybe at these secondary distribution points, but not at the actual Ontology URI, therefore not following Linked Data principles. 

Also, because SWEET is so big, it is normal to download the whole thing to cache locally. 
So really need a distro that provides the alternative serializations zipped up. 

.owl files are not supported by TopBraid composer. Since this is my usual RDF IDE, I have to jump a lot of hoops to get SWEET loaded, usually too many.

**Comment by lewismc** [comment]
ack @dr-shorthair I think that SWEET 2.4 could easily address this issue. There is some basic discussion to be had regarding how and when the different serializations are to be generated e.g. by the release manager prior to a release or by a developer upon ever new commit to the codebase.
What are your thoughts?
As mentioned, the [COR](http://cor.esipfed.org/) as an example provides content negotiation for following formats
<img width="118" alt="screen shot 2017-07-24 at 5 20 44 pm" src="https://user-images.githubusercontent.com/1165719/28550258-7766ffb6-7094-11e7-9323-0cfca1068cfd.png">

**Comment by carueda** [comment]
> Sorry the COR is currently down. As you may have seen in the mailing list, I just emailed our ECITE contact to look into the issue asap.

**Comment by carueda** [comment]
Thanks @lewismc for the COR reference.

Since COR is currently down, here's an example using https://xdomes.org/ont/xdomes/sensorType. If you just open this URL in your browser, then content negotiation will make the underlying ORR server resolve the URL to the usual HTML presentation because browsers include `text/html` in the Accept header of the request.

Other supported formats include:

|Accept header | Doc link |
|---------------|---------|
| `application/rdf+xml`   | https://www.w3.org/TR/REC-rdf-syntax/
| `application/json+ld`   | http://www.ietf.org/rfc/rfc6839.txt
| `text/n3`               | http://www.w3.org/TeamSubmission/n3/
| `text/turtle`           | http://www.w3.org/TeamSubmission/turtle/
| `text/plain`            | http://www.w3.org/TR/2004/REC-rdf-testcases-20040210/
| `application/n-quads`   | http://www.w3.org/TR/2013/NOTE-n-quads-20130409/
| `application/trig`      | http://www.w3.org/TR/2013/WD-trig-20130409/
| `application/rdf+json`  | https://dvcs.w3.org/hg/rdf/raw-file/default/rdf-json/index.html

For example, using the [HTTPie](https://httpie.org) command line tool:

```bash
$ http get https://xdomes.org/ont/xdomes/sensorType Accept:application/json-ld
```

```json
{
    "@context": {
        "@vocab": "https://xdomes.org/ont/xdomes/sensorType/",
        "LongName": {
            "@id": "https://xdomes.org/ont/xdomes/sensorType/LongName"
        },
        "Reference": {
            "@id": "https://xdomes.org/ont/xdomes/sensorType/Reference",
            "@type": "@id"
        },
        "ShortName": {
            "@id": "https://xdomes.org/ont/xdomes/sensorType/ShortName"
        },
       ...
    },
    "@graph": [
        {
            "@id": "./",
            "@type": "owl:Ontology",
            "description": "This is a collection of sensor types in the enviro-sensing community.",
            "hasContributor": [
                "Mike Botts",
                "Carlos Rueda"
            ],
            "hasCreator": "Janet Fredericks",
            "hasResourceType": "http://mmisw.org/ont/mmi/resourcetype/sensor",
            "keywords": "sensor",
            "name": "SensorType",
            "origMaintainerCode": "xdomes",
            "reference": "http://www.opengeospatial.org/standards/sensorml"
        },
       ...
        {
            "@id": "windVane",
            "@type": "SensorType",
            "LongName": "windVane",
            "ShortName": "windVane",
            "definition": "A wind vane is an instrument that measures wind velocity using a propellor and direction using the mechanical mechanism (tail) to associate the direction of the sensor to determine the wind direction,"
        }
    ]
}
```

**Comment by dr-shorthair** [comment]
#24 supersedes this issue.

**Comment by dr-shorthair** [comment]
Ensure that every SWEET URI - for a class, property, individual, and also ontology graph or file - dereferences (resolves) to a structured resource

meet reasonable expectations of http content negotiation - html, owl/xml, rdf/xml, turtle, n-triples, JSON-LD

Redescribe, rename and re-open this issue to retain connection to discussion. Close #24.

**Comment by carueda** [comment]
@dr-shorthair @lewismc @graybeal 
Per the current status of things, seems like this entry could be closed as resolved?

In short, here's the status as I can see it:

- all sweet files are now captured and stored in turtle format here at github.
- per progress on #51, the COR-powered dispatch of `sweetontology.net/*` allows to resolve requests on a number of typical serializations via content-negotiation or `format` parameter (see also https://github.com/mmisw/orr-ont/issues/55)

**Comment by lewismc** [comment]
+1 @carueda things are really moving on

**Comment by dr-shorthair** [comment]
#51 deals with the implementation
