### ISSUE TITLE
Ontology documentation

### ISSUE THREAD

**Issue by dr-shorthair** [ESIPFed/sweet#19]
The SWEET ontology has very limited documentation/metadata. 
Suggest following the LOV guidelines http://lov.okfn.org/Recommendations_Vocabulary_Design.pdf , or using OMV http://mayor2.dia.fi.upm.es/oeg-upm/index.php/en/downloads/75-omv/index.html to embed key documentation concerning SWEET as a whole.

**Comment by lewismc** [comment]
Do you have a link to the LOV guidelines @dr-shorthair ?

**Comment by dr-shorthair** [comment]
editted the issue descrption to include link

**Comment by cmungall** [comment]
LOV docs are good but I note they don't recommend owl:versionIRI. I recommend all released versions of SWEET are permanently available via a permanent URL that is recorded in the versionIRI.

Note: provided the ontology fits in github it's possible to use the github release mechanism to make version management easy:

https://github.com/INCATools/ontology-starter-kit/blob/master/template/src/ontology/README-editors.md#release-manager-notes

**Comment by lewismc** [comment]
@nicholascar FYI :)

**Comment by dr-shorthair** [comment]
@cmungall the link to version instructions is broken - do you know where it is now?

**Comment by nicholascar** [comment]
Hi all, please check out the capabilities of pyLODE to handle ontology documentation: https://github.com/rdflib/pyLODE/. Note that the tool's repo give a fair bit of guidance on 'good' ontology metadata: https://github.com/RDFLib/pyLODE/blob/master/SNIPPETS.rst.

I'm keen to hear about SWEET's perceptions of good class and property documentation (pyLODe handles labels, usage nodes, descriptions and normal OWL constructs but are there special SWEET requirements) and SWEET's potential use of pyLODE to export ontologies in HTML or Markdown. 

See the following SWEET ontologies documented in Markdown using pyLODE with no tweaking:

https://github.com/nicholascar/sweet/blob/master/src/human.md
https://github.com/nicholascar/sweet/blob/master/src/matr.md
https://github.com/nicholascar/sweet/blob/master/src/phen.md
https://github.com/nicholascar/sweet/blob/master/src/proc.md
https://github.com/nicholascar/sweet/blob/master/src/prop.md
https://github.com/nicholascar/sweet/blob/master/src/rela.md
https://github.com/nicholascar/sweet/blob/master/src/repr.md

**Comment by graybeal** [comment]
COR automatically provides access to submitted versions of locally managed ontologies, including automatically generating the version identifiers using the submission. (Which at one level is very easy, as in "0 work required"; but there are subtleties about it that are not so easy, like embedding the version identifier within the ontology. So going back and accessing the ontology using the versioned identifier is easy, but if you want to distribute the ontology with self-documenting version, I think that requires mechanical work to add the version into it. (Is that right @carueda ?)

@cmungall I am imagining your solution properly embeds a version into each ontology?  Does the URL for accessing that version of the ontology use the version ID in the URL—that is, is the versioned ontology resolvable using the version string as part of the identifier? or only the non-versioned ontology?

**Comment by carueda** [comment]
> ... but if you want to distribute the ontology with self-documenting version, I think that requires mechanical work to add the version into it. (Is that right @carueda ?)

Sorry, I'm not quite following this ... maybe include this topic in a future COR telecon?

**Comment by cmungall** [comment]
We switched to using jinja2 for the main template:

https://github.com/INCATools/ontology-development-kit/blob/master/template/src/ontology/README-editors.md.jinja2

**Comment by lewismc** [comment]
In an attempt to consolidate this documentation issue, does anyone have any issue with us addressing it within the orr-portal issue? For example, please see https://github.com/mmisw/orr-portal/issues/130
If we want to create one for PyLODE then let's also create the plugin for orr-portal and do it over there. Closing this one off @dr-shorthair pleade re-open if you want to add.
