### ISSUE TITLE
Melting not a subclass of GlacierRetreat

### ISSUE THREAD

**Issue by smrgeoinfo** [ESIPFed/sweet#194]
sophcr:GlacierRetreat rdf:type owl:Class ;
                     rdfs:subClassOf sophcr:GlacialProcess ,
                                     sophsy:Retreat,
                                     soprocsc:Melting ;

subClassOf is not the correct relationship

**Comment by rduerr** [comment]
Agreed, melting and retreat are not parent classes of GlacierRetreat.  However, it isn't clear that complex relationships are really in SWEET's remit.  The clearest short term fix would be to simply remove those two subclass statements (so that is what I am doing).
