### ISSUE TITLE
[BUG] can't actually access the ontology via my browser

### ISSUE THREAD

**Issue by graybeal** [ESIPFed/sweet#198]
## Description

I'm seeing a social and ontological issue with accessing SWEET as an ontology, it's actually very hard to do. 

If I go to sweetontology.net, there is no information that I can find (my wife will tell you I'm a bad searcher, so caveat lector) that says how to actually access the ontology. (I thought it was /sweetALL, but that didn't work.) There is no pointer to /sweetAll, no pointer to COR, there is only extensive documentation about how we did everything.

Eventually I realized it was /sweetAll. But again, I didn't find the ontology there. I found the pyLODE presentation of the ontology, but that wasn't what I wanted, I really wanted the OWL file.

By mousing all the way to the bottom I got to a link that said RDF (Turtle), which points back to http://sweetontology.net/sweetAll. So I still can't see the ontology.

Because I'm an 'expert', I know I can go to COR, and find the link there that says View/Download in RDF. I click on that, and the download happens (although it isn't obvious that it happened, just a new tab appeared in my browser downloads area). But I still can't view it, or know that the link to use to view it is. 

The reason I wanted all that is to [view it in WebVowl](http://www.visualdataweb.de/webvowl/#iri=https://raw.githubusercontent.com/ESIPFed/sweet/master/src/sweetAll.ttl)—take a while but it's cool that it works. I would expect content negotiation to make the first link work, but it doesn't, it gives a parse fail

## What would you like to see changed?

The top of the SWEET page should have the following right after the first sentence: 
[View in pyLODE](https://sweetontology.net/sweetAll) &nbsp; [View in WebVowl](http://www.visualdataweb.de/webvowl/#iri=https://raw.githubusercontent.com/ESIPFed/sweet/master/src/sweetAll.ttl)
[View in ESIP COR](http://cor.esipfed.org/ont?iri=http://sweetontology.net/sweetAll)  &nbsp; [View in GitHub](https://github.com/ESIPFed/sweet/blob/master/src/sweetAll.ttl)
[View RDF raw](https://raw.githubusercontent.com/ESIPFed/sweet/master/src/sweetAll.ttl) &nbsp; [Download RDF](http://cor.esipfed.org/ont/api/v0/ont%3Firi=http://sweetontology.net/sweetAll)  

And I think we should figure out why content negotiation didn't work with WebVowl.

## Attribution

If you would like a nano-attribution, please use the [following guidance](https://github.com/ESIPFed/sweet/wiki/SWEET-Class-Annotations-Proposal).

## Labeling your issues 

Please make use of our [labels](https://github.com/ESIPFed/sweet/labels)... this really helps us to better understand and prioritize your issue.

**Comment by lewismc** [comment]
Hi @graybeal you can just access http://sweetontology.net/sweetAll.ttl 
From a browser this will activate pyLODE. From curl you need to provide the Content-Type header to obtain the TTL.
