### ISSUE TITLE
At least one EDITOR needs domain expertise in the part of the ontologies for being changed

### ISSUE THREAD

**Issue by rduerr** [ESIPFed/sweet#2]
Anyone can propose changes to the SWEET ontologies via github issues; but there needs to be some level of domain expertise (as well as semantics expertise) in the EDITORIAL team that reviews and approves proposed updates.

**Comment by lewismc** [comment]
Hi @rduerr this is understood and we have been doing consensus building in that vein. I think we can close. Let's reopen this conversation when we finally get YAMZ running... which I am working on doing.
