### ISSUE TITLE
Annotation of SWEET terms

### ISSUE THREAD

**Issue by dr-shorthair** [ESIPFed/sweet#20]
Very few SWEET terms have human-readable annotations. 
The definitions of SWEET terms are implied by the axiomatization, which is often incomplete. 

Every SWEET term should have at least
rdfs:label (and/or skos:prefLabel or dct:title) for the name
rdfs:comment (and/or skos:definition or dct:description) for a text definition

**Comment by charlesvardeman** [comment]
ENVO defines annotation properties:
has_broad_synonym
has_exact_synonym
has_narrow_synonym

That may be useful for lightweight alignment to terms in other vocabularies and ontologies without creating a strong ontological commitment.

**Comment by dr-shorthair** [comment]
This is derived from standard Thesaurus terminology. This formaulation appears in the SKOS mapping relationships `skos:broadMatch`, `skos:exactMatch`, `skos:narrowMatch` (as well as `skos:closeMatch` and 'skos:relatedMatch` - which support mapping a concept to a related on in a different scheme. OTOH text label options are managed with `skos:prefLabel`, `skos:altLabel` (and `skos:hiddenLabel`). 

Do the ENVO annotations: 
1.  associate a class with one or more _text labels_
2.  provide a mapping of an ENVO class to a concept in another vocabulary? 

These are different notions.

**Comment by brandonnodnarb** [comment]
I added `rdfs:label` properties to everything with a full URI in every ttl file (not blank nodes).  I split the text using the camel case values in the stem of the URI.  So, for example, `hydr:CascadingWater` received the label:  `rdfs:label` "Cascading Water"`@en .`

I have tested each file and none have returned an error (other than the errors already mentioned in previous issues).  I am using Protege 5.5.  

Is there any objection to a single pull request with all the labels added?

**Comment by rduerr** [comment]
not from me...  label away!

**Comment by cmungall** [comment]
I recommend using all lowercase except for proper names. If applications
need to uppercase something they can, but the converse is not true.

By the same token you can't algorithmically reliably downcase without
knowing what the proper names are.. but I suggest starting with this and
uppercasing as required.

>

**Comment by dr-shorthair** [comment]
+1 to @cmungall recommendation. 
For similar reasons, don't include any unnecessary punctuation - e.g. no full-stop/period at the end of the label

**Comment by brandonnodnarb** [comment]
done.  I'll issue a pull request after I test.
  
@dr-shorthair, I didn't notice any punctuation, but there are few rogue underscores of which I'm aware and will clean up.  There are decimals in the numerical labels, primarily in `stateTimeGeologic.ttl`

There are several hundred `owl:sameAs` and `owl:equivalentClass` relationships that appear to be a mechanism for adding, essentially, alternate labels (i.e. `skos:altLabel`).   I will create a separate issue for this discussion.  Relevant here as a good chunk of these are acronyms (and should be capitalised).

**Comment by dr-shorthair** [comment]
`owl:sameAs` axioms come with serious consequences. It says that you can merge the properties of the two resources - they are the same thing, so they share all properties. 

`owl:equivalentClass` is similarly strong, but also entails that both participants are `rdfs:Class`. 

If it is only alternative labels, then probably best use the predicate that supports this without any further entailments - i.e. `skos:altLabel`.

**Comment by lewismc** [comment]
Closing this issue as the initial labels have been provided as per the above suggestions/guidance in #117 

I am a fan of providing rdfs:comment (and/or skos:definition or dct:description) for a text definition however this should be addressed in a separate ticket.
