### ISSUE TITLE
A SWEET survey

### ISSUE THREAD

**Issue by brandonnodnarb** [ESIPFed/sweet#216]
Relating to the discussion on #211 (and #49, and #159 and...) it may be quite informative to find out who or whom is using SWEET, how it used, how it may be used in the future, etc.

For context, we performed a similar task for the [Agrisemantics WG](https://rd-alliance.org/groups/agrisemantics-wg.html) and the results were actually pretty interesting ([output 2](https://www.rd-alliance.org/deliverable-2-use-cases-and-requirements) is most relevant here).  Many, if not all, of these questions could be pertinent to this crowd.

Obviously there would need to discussion around format and content.  Initially I encourage replies answering the following:
a) Would information from a survey of this nature be useful to you?
b) Would you yourself be willing to fill out such a survey?
c) Which questions would you want answered through such a survey? 
d) Are you willing to contribute?

I would like answers for the following (no particular order yet):
1. Have you ever heard of SWEET (Semantic Web for Earth and Environmental Terminology)?
2. Have you ever used SWEET?
      * why or why not?
3. Which semantic resources (ontologies, semantic models, thesauri, linked data, etc.) do you use?
      * (terminology can be sticky, I would try to be as inclusive as possible)
4. How are the resources used (or re-used)?
5. Are the resources re-used public or private?

There are others, but let's start here and see if it goes anywhere. :)

**Comment by graybeal** [comment]
Suggest changing your numbering scheme to letters for one of those two lists.

Are questions 3 through 5 in the second list about SWEET resources? Some may be confused, thinking of SWEET as 1 resource, and assume they are about other resources.

1) Yes, useful, if widely enough distributed. Actually, question one is a problem. If I haven't heard of SWEET I'm unlikely to answer the questionnaire, so the results are biased. Ditto if I haven't used it. So having a controlled audience somewhere would be nice.

2) I would be willing.

3) Would "Where do you access SWEET?" be a useful question?  How about something like "We are considering defining SWEET's mission as a tagging, mapping, and definitional resource for common science concepts. Would this be desirable in your judgment, and if not what would you propose for SWEET's mission?"

4) Already contributing, a bit.

**Comment by brandonnodnarb** [comment]
Done: https://forms.gle/DMbLzDuECEPom4Ms8
