### ISSUE TITLE
Remove version number from SWEET namespace / URI stem

### ISSUE THREAD

**Issue by dr-shorthair** [ESIPFed/sweet#22]
SWEET published by NASA included the SWEET version number in the term URI. 
This meant that same terms have different URIs even with the same intention and implied definition, in different versions of SWEET. This makes references to SWEET in datasets totally dependent on the SWEET version, and undermines the goal of SWEET which is to provide a bridging vocabulary. 

If there is no change of intention or definition, then there is no need for a change of denotation (URI). 
Moving forward, I suggest not including a version number in term URIs. 
If a term definition of intention changes (... in a future 'version' of SWEET) then just give it a different URI, but the URIs of terms within SWEET should not be tied to releases of the Ontology as a whole.

**Comment by lewismc** [comment]
Yes I agree @dr-shorthair and this in a whole stems to basic URI construction practice. Please see #6 for ongoing conversation on this topic.

**Comment by lewismc** [comment]
@dr-shorthair I've also created a pull request over at #34 please scope it out. Thank you.

**Comment by lewismc** [comment]
This was addressed in #34

**Comment by lewismc** [comment]
For more information on how this is now encoded please see https://github.com/ESIPFed/sweet/issues/14
