### ISSUE TITLE
Mappings to existing external vocabularies

### ISSUE THREAD

**Issue by dr-shorthair** [ESIPFed/sweet#23]
The scope of SWEET overlaps with existing external vocabularies in a number of areas. 
While SWEET has the distinct advantage of providing a unified vocabulary for much of the physical natural sciences, in some areas the external/prior art is very strong, and arguably should take precedence over SWEET [1] .

To support SWEET users, mappings from SWEET to key existing external vocabularies should be provided as part of the SWEET distribution. These should probably be provided as separate graphs, which import SWEET and the external vocabulary, and then include axioms expressing the mappings. 

[1] For example, many of the OBO Foundry ontologies (http://www.obofoundry.org/), QUDT (http://www.qudt.org/release2/qudt-catalog.html), and the International Chronostratigraphic Chart from the International Commission for Stratigraphy (published as an RDF vocabulary and service here: http://resource.geosciml.org/classifier/ics/ischart/ ).

**Comment by dr-shorthair** [comment]
See discussion of relation to ENVO at #33

**Comment by cmungall** [comment]
(originally posted in #33):

highly preliminary work mapping SWEET to OBOs: https://github.com/cmungall/sweet-obo-alignment (happy to move to ESIPFed org when more mature).

@lewismc asked if the OBO alignment tools would work for aligning SWEET to non-OBO ontologies. It should do. It will need tweaked for example if an ontology uses a custom property for synonyms, but this should be easy.

Of course other mappers are available, if we want to try multiple that is fine. For the OBOs my personal interest is going beyond simple mapping and assignment of strict inter-ontology logical axioms.

**Comment by lewismc** [comment]
I would like to close this generic issue and instead focus on specific issues where we can get sincere peer review. Please re-open @dr-shorthair if you feel this is unfair. Thanks

**Comment by dr-shorthair** [comment]
GitHub issue tracker is relatively flat, else this could have been a higher-level issue composed of multiple sub-issues.

**Comment by lewismc** [comment]
Correct.
