### ISSUE TITLE
Use of xsd:decimal instead of xsd:double for conversion factors

### ISSUE THREAD

**Issue by jmkeil** [ESIPFed/sweet#231]
Using a [comparison of unit ontologies with ABECTO](https://github.com/fusion-jena/abecto-unit-ontology-comparison) I became aware that SWEET uses `xsd:double` to represent conversion factors and offsets. I think, instead `xsd:decimal` should be used, as binary floating point datatypes are not able to exactly represent many of the conversion values. Especially 0.1, 0.01, 0.001, … can not be represented. Only the lexical representation seems to be exact. However, the lexical to value mapping will map them to a slightly different value. This runs the risk of numerical problems in applications. I outlined this in detail in [arXiv:2011.08077](https://arxiv.org/abs/2011.08077).

**Comment by dr-shorthair** [comment]
+1 from me. 

I just made related PR in QUDT - https://github.com/qudt/qudt-public-repo/pull/311 
and OM is coming up behind https://github.com/HajoRijgersberg/OM/issues/42

**Comment by lewismc** [comment]
@jmkeil thanks for registering the issue. Are you able to provide a pull request? If not, one of us can get around to it.
