### ISSUE TITLE
[BUG] A moraine is not a plain of any kind!

### ISSUE THREAD

**Issue by rduerr** [ESIPFed/sweet#280]
## Description

The term moraine is currently classed as a type of plain (http://sweetontology.net/realmLandGlacial/Moraine) and it isn't clear from the definitions what the difference between glacial moraine (http://sweetontology.net/realmLandGlacial/GlacialMoraine) and just plain moraine is.  

## What would you like to see changed?

Please update the hierarchy to move it out from under glacial plain (actually with the exception of the terms that end in the word plain, all of the terms under glacial plain should be moved up to be parallel concepts to glacial plain at the very least).

## Attribution

(https://orcid.org/0000-0003-4808-4736)

**Comment by r0sek** [comment]
Agree.

1. Glacial Plain and Moraine (http://sweetontology.net/realmLandGlacial/Moraine) are parallel concepts a both are formed by glacier-related processes, so Moraine should be moved out from under Glacial Plain
2. Glacial Moraine (http://sweetontology.net/realmLandGlacial/GlacialMoraine): moraines are exclusively formed by glacier-related processes, so "glacial moraine" is redundant and incorrect, and its SWEET entry has no definition, so it should be removed.

**Comment by rduerr** [comment]
Agreed with @r0sek

**Comment by r0sek** [comment]
@brandonnodnarb has made the changes in Protégé and will create pull request/merge when branch is uploaded
