### ISSUE TITLE
Identify Subject Matter Experts for Review and Governance

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/sweet#3]
As a community, we've acknowledged that we need SMEs to ensure the accuracy and integrity of SWEET.
From previous documentation on SWEET, I've identified the following areas which we 'may' need SMEs for

**Integrative Topics**
 * Natural Phenomena (Macroscale)
 * Human Activity
 * Data

**Faceted Topics**
 * Living Substances
 * Non-Living Substances
 * Physical Processes (microscale)
 * Earth Realm
 * Pysical Properties (observation)
 * Space
 * Time
 * Units
 * Numerics

Are there any others?

**Comment by lewismc** [comment]
The [Global Change Master Directory (GCMD) Keyword Governance and Community Guide Document](https://cdn.earthdata.nasa.gov/conduit/upload/5182/KeywordsCommunityGuide_Baseline_v1_SIGNED_FINAL.pdf) provides **Subsection 3.3 Change Process Overview** which we could use as guidance...

**Comment by rduerr** [comment]
So the problem that I have with this is insufficient specificity.  For example, I'd be happy to sign up for cryospheric terms.... but that isn't on the list.

**Comment by lewismc** [comment]
OK @rduerr, well let's add that area to the roster of interested members. I'm going to overhaul the document [here](https://esipfed.github.io/stc/publishing-snapshots/FPWD-2016-08-01-SWEET/index.html), so we can begin capturing this stuff @rduerr. It is not intentional that that area was left out, it's just that I didn't know enough about it to state it explicitly right now. Thanks for writing here to register interest.

**Comment by fils** [comment]
@lewismc I'd be happy to help in the area of Geologic time.  I'd love to try and help with connections between Simon's OWL time based Geologic Timescale Ontology https://github.com/dr-shorthair/GeologicTimeScale and SWEET.  I know several others who would love to be involved too.  I will point them at the repo and this issue.    Is there any formal mechanism you would like us to self identify?  If I can get some interested parties together I suspect we can assess the functional needs of our community re: the ontologies.  I'll try and start some discussions with them.  Perhaps under a separate issue.

**Comment by lewismc** [comment]
Hi @fils thanks, I think over time, we will most likely need a separate group (subgroup of the semantic tech committee) which works on SWEET. I would suggest, we start overhauling the document [here](https://esipfed.github.io/stc/publishing-snapshots/FPWD-2016-08-01-SWEET/index.html) which I've obviously borrowed from the W3C SSN effort. For the time being I think people should just tag themselves here and we can take it fro there. I'm going to start work on the document linked above.

**Comment by alisonboyer** [comment]
Hi, I am willing to review natural phenomena and living substances. I'm with the NASA DAAC at Oak Ridge National Lab, specializing in data archival for ecological and biogeochemical data.

**Comment by tbs1979** [comment]
I am interested in being involved and see how the GCMD Keyword can fit into this.

**Comment by lewismc** [comment]
Thank you both @alisonboyer and @tbs1979 theses are very important areas so thank you for coming forward. Your interest is noted and you will both be included in any talks going forward thank you.

**Comment by CommonClimate** [comment]
Hi! I'm a PI on the NSF-funded EarthCube project [LinkedEarth](http://linked.earth). I'd like to sign up as a subject matter expert for climate and paleoclimate data. For the latter we have a [fairly robust ontology](http://linked.earth/ontology/) that could help extend SWEET in this direction. Please let me know the best way to participate.

**Comment by lewismc** [comment]
Excellent @CommonClimate this is brilliant, thank you for registering your interest. I think we will be discussing this at our next ESIP SemTech committee meeting. I'll ping you in good time so you are aware and involved in the organization moving forward. Thanks.

**Comment by CommonClimate** [comment]
My pleasure @lewismc . Ping away.

**Comment by narock** [comment]
@fils @lewismc W3C is looking for implementations of OWL Time. The connection between Simon's work, SWEET, and OWL Time could be a good fit for this: https://www.w3.org/blog/news/archives/6346

**Comment by lewismc** [comment]
ack I agree @narock. I'm not really in a position to lead that work... I don't know enough about OWL Time tbh. Can you tag Simon here?

**Comment by narock** [comment]
@lewismc I think @fils already reached out to Simon. I will check, and if not, I'll tag him.

**Comment by xgmachina** [comment]
@lewismc Nice to see many familiar colleagues here. I will be glad to contribute to topics of Space, Time and Data provenance, but will not limit only to them - SWEET is a big ontology with so many topics of interest.

**Comment by lewismc** [comment]
Excellent @xgmachina, thank you for registering interest. We will be in touch shortly.

**Comment by pbuttigieg** [comment]
@lewismc - we're happy to add insight from or sync ENVO's branches here. Our community contributors (often subject matter experts) have helped build some good branches over the years.

**Comment by lewismc** [comment]
Excellent @pbuttigieg thank you for noting your interest.

**Comment by linepouchard** [comment]
Hi Lewis and all:
I am happy to contribute to Data and related processes.

**Comment by lewismc** [comment]
Excellent @linepouchard thank you

**Comment by lewismc** [comment]
@rduerr @alisonboyer @tbs1979 @CommonClimate @pbuttigieg can you all please make a request to join the following group https://github.com/orgs/ESIPFed/teams/semtech/members this way you will be included in notifications. Thank you

**Comment by tbs1979** [comment]
@lewismc at one point in an earlier version of SWEET, GCMD keywords were incorporated. Is there any plan from the SWEET end to incorporate or link the GCMD keywords in again?

**Comment by graybeal** [comment]
I wonder if these relations might be better published in a separate file(s)? That would allow independent maintenance/workflows, and possibly easier reuse of the mappings.

Depends on how integral that info is to SWEET, I guess.

________________________________

**Comment by lewismc** [comment]
We are getting into the terrain of ontology alignment here folks... which I think should be addressed on a separate thread. I'm going to put some work into the current [SWEET Working document](https://esipfed.github.io/stc/publishing-snapshots/FPWD-2016-08-01-SWEET/index.html) which I will style after out [SRI Use Cases and Requirements documentation](https://esipfed.github.io/stc/UseCases/STCUseCasesAndRequirements.html)

**Comment by edshred2000** [comment]
I'm interested in contributing expertise to formats, provenance and data processing, as well as ocean phenomena expertise.

**Comment by lewismc** [comment]
Thank you @edshred2000, noted

**Comment by dr-shorthair** [comment]
International Chronostratigraphic Chart - 2016-12 version - formalized in SKOS and OWL-Time, is now available through Research Vocabularies Australia: 
https://vocabs.ands.org.au/international-chronostratigraphic-chart-2016 
see 
http://vocabs.ands.org.au/repository/api/lda/csiro/international-chronostratigraphic-chart-2016/2016-12-v3/resource?uri=http://resource.geosciml.org/vocabulary/timescale/isc2016-12 

The individual http://resource.geosciml.org/classifier/ics/ischart/ URIs, such as http://resource.geosciml.org/classifier/ics/ischart/Phanerozoic , are now set up to resolve to this service, so it is a proper Linked Data resource. 
Note that GeochronologicEra and GeochronologicBoundary resources are formalized as OWL individuals, rather than OWL classes, which I think is inconsistent with SWEET's classist approach.

**Comment by lewismc** [comment]
Thank you for input @dr-shorthair are you interested in being involved in the SWEET Ontology Interest Group? We can make sure your comment makes it onto the agenda.

**Comment by lewismc** [comment]
>  Note that GeochronologicEra and GeochronologicBoundary resources are formalized as OWL individuals, rather than OWL classes, which I think is inconsistent with SWEET's classist approach.

... and yes @dr-shorthair you are correct with the above statement.

**Comment by dr-shorthair** [comment]
There was a time when I would have entered an argument about this, but I think we are all more relaxed now. By defining all concepts as OWL classes you can take advantage of OWL axiomatization of the class definition, which is good. OTOH by defining classes (like GeochronologicEra) with individual members (like Cenozoic, Wenlockian, etc) you can say more about how they are used in datasets, using rdfs:range/domain and owl:Restriction constraints which apply to all the individual members of a class, not subclasses. OWL2 punning allows us to mix and match a bit, though also at some reasoning costs. But overall if we can be a bit accepting I think it can all work.

**Comment by dr-shorthair** [comment]
@fils Note additional axiomatization of timescale nesting logic here, using OWL-Time predicates
http://resource.geosciml.org/ontology/timescale/gts/w3c.ttl 

Not really tested yet, but you can see the principle.

**Comment by lewismc** [comment]
I've added a note to our release announcement
https://github.com/ESIPFed/sweet/wiki/Community-Announcements
It calls for Subject Matter Experts... that is probably the best way we can get the message out there.
