### ISSUE TITLE
Investigate presence of blank nodes throughout SWEET

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/sweet#45]
An example can be found at https://github.com/ESIPFed/sweet/blob/master/humanAgriculture.ttl#L39-L40

**Comment by dr-shorthair** [comment]
It is completely normal for owl:Restriction classes (and unions and intersections) to be formulated as blank nodes. 
See 
https://en.wikipedia.org/wiki/Blank_node#Anonymous_classes_in_OWL

**Comment by cmungall** [comment]
The OWLAPI will render turtle such that the blank node ids will generally be hidden by nesting. Not sure if there is an option in Jena to do this.

Not directly related to the ticket title, but related to the subject of standard serializations:

I recommend a CONTRIBUTING.md that amongst other things states a recommended library for rendering the turtle, to avoid spurious diffs. See https://douroucouli.wordpress.com/2014/03/30/the-perils-of-managing-owl-in-a-version-control-system/

**Comment by dr-shorthair** [comment]
> recommended library for rendering the turtle

This would need to be available as a 'converter'. We do not control the libraries embedded in the IDE's that we use (e.g. Protege, TopBraid Composer).

**Comment by cmungall** [comment]
Do you pre/proscribe different IDEs? I don't see any recommendations
https://github.com/ESIPFed/sweet/blob/master/CONTRIBUTING.md

We're massively OWLAPI-centric in the OBO world (Protege, Robot, OWLtools, Scowl, ....). It may be limiting for this community to impose such a restriction... but it saves a lot of headaches.

**Comment by lewismc** [comment]
> Do you pre/proscribe different IDEs? I don't see any recommendations

The answer is no, we don't currently recommend use of any IDE's... seeing as right now there is a small pool of community developers submitting code, I suggest that we adopt the OWL-centric model as well unless someone objects...

**Comment by dr-shorthair** [comment]
I use TopBraid on my desktop. TTBOMK it does not use OWLAPI. 
Its Turtle serialization is very predicatable, but is not OWLAPI. 
I'm not about to drop TopBraid as it would seriously impact my productivity. 
That's why I suggest a converter to canonical form for diffs. 
Could be deployed using a post-commit hook?

**Comment by cmungall** [comment]
Interesting - apologies for the naive questions, I know nothing about how sweet is edited. I have created a new ticket for the creation of an editors guide #46 which would be explicit about editing practices like this.

If you do decide on OWLAPI as canonical form then robot can be used. But be careful, watch for cryptic OWL parse errors.

**Comment by dr-shorthair** [comment]
Not naive at all. Community-based governance is interesting.

**Comment by carueda** [comment]
Jena should also be able to use nesting for printing blank nodes for turtle "where possible":

> The pretty printed versions of Turtle and TriG prints data with the same subject in the same graph together. All the properties for a given subject are sorted into a predefined order. RDF lists are printed as (...) and **[...] is used for blank nodes where possible**.

(https://jena.apache.org/documentation/io/rdf-output.html#pretty-printed-languages)

**Comment by lewismc** [comment]
Hi Folks, closing this one off. If an addition to CONTRBITION.md is required, let's address that on another ticket. Thanks for all the comments.

**Comment by dr-shorthair** [comment]
I looked at some Turtle files generated through OWLAPI and the blank nodes appeared at the bottom of the file, rather than being nested. 
I couldn't actually see how they got attached to the context which they belonged in ...
