### ISSUE TITLE
slash vs. hash

### ISSUE THREAD

**Issue by carueda** [ESIPFed/sweet#48]
I think the particular aspect of slash vs. hash recently discussed in https://github.com/ESIPFed/sweet/issues/46 deserves its own entry for further discussion and resolution.

**Comment by carueda** [comment]
@graybeal  @dr-shorthair @lewismc @cmungall @brandonnodnarb 

Just in case we could just apply a voting process here (somehow to avoid the need for further, perhaps unnecessary lengthy discussions), I vote for **slash**. 

Any other suggestions?

**Comment by graybeal** [comment]
Me too. I see no down side and considerable up side (and not just for COR purposes).

**Comment by lewismc** [comment]
+1 for slash, some documentation on this can be found at https://www.w3.org/wiki/HashVsSlash
In the case of the slash, no resources in SWEET are too large for everything before the final slash such that they will present a problem for responses and client interpretation.

This is however going to be a complete and utter PITA to implement...

**Comment by graybeal** [comment]
Both BBEdit and tricky sed commands can change it in every file at once. Mm, maybe.

john

**Comment by dr-shorthair** [comment]
Looks like the ISSUE-27 branch did not get processed to convert # --> / URIs. 
I also note that many many many of the namespace prefixes in the source files are bound to URI without a "/" on the end, so these prefixes are just so much noise!

**Comment by dr-shorthair** [comment]
Many many many of the namespace prefixes in almost all of the source files are bound to URI without a "/" on the end, so these prefixes are often just so noise. 
Need to go through the source files systematically to ensure that the prefixes are bound to valid URI stems with a "/" (or "#") on the end.

**Comment by lewismc** [comment]
@dr-shorthair it looks like once this is resolved it may justify a SWEET 3.1.0 release... I'll have a look tomorrow.

**Comment by dr-shorthair** [comment]
Yes - this also explains why I was seeing soooo many namespaces in my TopBraid IDE.

**Comment by carueda** [comment]
@dr-shorthair @lewismc Please provide concrete pointers/examples demonstrating the issue.  I'm a bit confused. Thanks.

**Comment by carueda** [comment]
Ah, you want the `#-/` conversion to be applied on your PR's branch!  I would have expected a separate request for this, not re-opening this issue.  Well, please confirm that's what you want.  (BTW, I wonder if it would be safer to recreate your changes on a new branch?)

**Comment by dr-shorthair** [comment]
> (BTW, I wonder if it would be safer to recreate your changes on a new branch?) 

That's what I did, eventually. Tried to re-base, but the conflicts were all tangled up with the NS issue. 
I probably used the wrong sequence. Once a year I have a git/github meltdown and learn some lessons.

**Comment by graybeal** [comment]
On what basis was the original issue closed? I can't tell if we agreed on / and that is now implement, or many other things happened but nothing happened on the original question.

**Comment by dr-shorthair** [comment]
PR was merged. "/" URIs throughout. All good. Ancient history now.

**Comment by brandonnodnarb** [comment]
In summary, there was agreement on using slashes, not hashes (/ not #) and this has been addressed throughout.  Assuming this is accurate, and resolved, this issue can be closed, no?

**Comment by graybeal** [comment]
Yes, I'll be happy to volunteer to save you the trouble.
