### ISSUE TITLE
sweetontology.net ontology/term resolution

### ISSUE THREAD

**Issue by carueda** [ESIPFed/sweet#51]
Entering this ticket to capture and track testing, observations, suggestions and any pending aspects involving the recently enabled COR powered dispatch of sweetontology.net,
 see https://github.com/ESIPFed/sweet/wiki/COR-powered-dispatch-of-sweetontology.net.

In summary, input is welcome regarding the desired HTML dispatch (if any) for the ontologies and terms, and, in general, about any issues or enhancements.

Ah, one other piece is the desired dispatch of the base name http://sweetontology.net/ :
- redirect? if so, to what; or
- provide html file to replace current placeholder contents at `/var/www/html/sweetontology.net/index.html`
- other?

**Comment by dr-shorthair** [comment]
Also might consider supporting the common community expectation that HTTP conneg (Accept header) can overridden with a well-known file suffix. 
e.g. requests like `http://sweetontology.net/stateTimeGeologic/Ypresian.ttl` is expected to return the same as `http://sweetontology.net/stateTimeGeologic/Ypresian Accept: text/turtle`

Strictly speaking the HTTP header should override everything, but our experience is that those people who know enough to add a suffix get frustrated if they don't get what they expected.

**Comment by carueda** [comment]
Agree. 

Please see https://github.com/mmisw/orr-ont/issues/55

**Comment by carueda** [comment]
@dr-shorthair @graybeal @lewismc FYI

COR just upgraded to v3.6.7 per implementation of https://github.com/mmisw/orr-ont/issues/55 regarding resolution of desired format via "file-type extension" in the ontology or term IRI.

Some term request examples for `http://sweetontology.net/stateTimeGeologic/Ypresian` on the command line using [HTTPie](https://httpie.org/) (remove `-pb` to also see the response header):

```bash
$ http -pb get http://sweetontology.net/stateTimeGeologic/Ypresian.ttl
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix err: <http://www.w3.org/2005/xqt-errors#> .
@prefix fn: <http://www.w3.org/2005/xpath-functions#> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix fti: <http://franz.com/ns/allegrograph/2.2/textindex/> .
@prefix keyword: <http://franz.com/ns/keyword#> .
@prefix nd: <http://franz.com/ns/allegrograph/5.0/geo/nd#> .
@prefix ndfn: <http://franz.com/ns/allegrograph/5.0/geo/nd/fn#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix xs: <http://www.w3.org/2001/XMLSchema#> .
<http://sweetontology.net/stateTimeGeologic/Ypresian> rdf:type <http://sweetontology.net/stateTime/Age> ;
  <http://sweetontology.net/relaTime/temporalPartOf> <http://sweetontology.net/stateTimeGeologic/Eocene> ;
  <http://sweetontology.net/relaTime/hasStartTime> <http://sweetontology.net/stateTimeGeologic/55.8MYA> ;
  <http://sweetontology.net/relaTime/hasEndTime> <http://sweetontology.net/stateTimeGeologic/48.6MYA> .
```

```bash
$ http -pb get http://sweetontology.net/stateTimeGeologic/Ypresian.json
{
    "names": [
        "property",
        "value"
    ],
    "values": [
        [
            "<http://sweetontology.net/relaTime/hasEndTime>",
            "<http://sweetontology.net/stateTimeGeologic/48.6MYA>"
        ],
        [
            "<http://sweetontology.net/relaTime/hasStartTime>",
            "<http://sweetontology.net/stateTimeGeologic/55.8MYA>"
        ],
        [
            "<http://sweetontology.net/relaTime/temporalPartOf>",
            "<http://sweetontology.net/stateTimeGeologic/Eocene>"
        ],
        [
            "<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>",
            "<http://sweetontology.net/stateTime/Age>"
        ]
    ]
}
```

```bash
$ http -pb get http://sweetontology.net/stateTimeGeologic/Ypresian.table
----------------------------
| property       | value   |
============================
| hasEndTime     | 48.6MYA |
| hasStartTime   | 55.8MYA |
| temporalPartOf | Eocene  |
| type           | Age     |
----------------------------
```

**Comment by lewismc** [comment]
Very nice.

**Comment by carueda** [comment]
I'm closing this entry as the central feature (semantic resolution) has been implemented and verified.

For the html part, I've just entered https://github.com/ESIPFed/sweet/issues/70
