### ISSUE TITLE
Updating entries at COR

### ISSUE THREAD

**Issue by carueda** [ESIPFed/sweet#52]
@lewismc @graybeal @dr-shorthair 

> Note that dispatch of `http://sweeteontology.net/*` is currently powered by the COR (see #51).

In general, this entry is to determine the conditions that will trigger the registration of a new revision of the SWEET ontologies at the COR upon changes in this git repo such that resolution through `http://sweeteontology.net/*` reflect the changes.

Possible conditions/considerations:

- Trigger a new revision at the COR upon any change to any of the ontology files.  The change logic can, at least initially, be based on a direct plain "diff" operation. (Later on, as deemed necessary, perhaps consider some mechanism a la owlDiff, or based on Jena's isIsomorphic operation, or something along those lines.)

- Update COR entries only upon a **published release** here at github. All ontology entries will be updated at the COR without inspection of contents.  Variations of this include:
  - Only update those entries having a change in `owl:versionInfo`. (Pressumably, a **release** will typically reflect a new `owl:versionInfo`.)
  - Only update those entries with some "diff."

Any other considerations/comments/etc?

**Comment by graybeal** [comment]
I agree that owl:versionInfo, or any other defined attribute, is insufficient. Often those are not changed by the person who is changing the ontology. For the fact the file has changed is enough indication the change should be captured.

The place that should be checked is the "public release" place, not a GitHub place that could have branch releases. So all COR should have to do is check to see if the file at the assigned place has changed. 

It should not check whether Imported files have changed, in my opinion (or you could make that an option, but the default is whether the source file itself has changed.

I see little advantage to checking whether the ontology model has changed (as opposed to just a text diff). If the text changes (even just the formatting) I would consider that a new revision.

**Comment by carueda** [comment]
@dr-shorthair @lewismc your thoughts please?

**Comment by lewismc** [comment]
@carueda i think that implementing the first solution you originally mentioned would be an excellent way for us to move forward.

**Comment by carueda** [comment]
@lewismc @graybeal @dr-shorthair 

This is implemented now. The code is at sweet-tools (please see [README](https://github.com/ESIPFed/sweet-tools/tree/master/sc/watchdog) there), and runs every 6hr as a cronjob on the COR machine:

```
29 */6 * * *  cd /home/centos/github/sweet-tools/sc/watchdog/ && ./watchdog.cronjob.sh >> watchdog.cronjob.out
```

Upon any updates, the registrations are done under the `sweetbot` account (which I created and made a member of the `esip` organization at COR). The relevant parameters are (excluding password of course):

```properties
endpoint   = "http://cor.esipfed.org/ont/api"
userName   = "sweetbot"
orgName    = "esip"
visibility = "public"
status     = "stable"
```
