### ISSUE TITLE
Discrepancies in Unit Ontologies

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/sweet#55]
Jan Martin Keil and Sirko Schindler from Friedrich Schiller University Jena, Germany have identified a list of instances, where SWEET (v2.3) differs from the definitions in the other ontologies they evaluated. A full listing is as follows
•	application area not linked to a quantity kind ("quantity"): 42 
•	quantity kind ("quantity") not linked to an application area: 458 
•	quantity kind ("quantity") not linked to an unit: 377 
•	unit not linked to a quantity kind ("quantity"): 54 
•	prefix not linked to an unit: 4 
Examples can be seen below

type | affected instance | our opinion on the matter
-- | -- | --
duplicate | http://sweet.jpl.nasa.gov/2.3/reprSciUnits.owl#FTU | duplicate   of http://sweet.jpl.nasa.gov/2.3/reprSciUnits.owl#FormazinTurbidityUnit
duplicate | http://sweet.jpl.nasa.gov/2.3/reprSciUnits.owl#permil | duplicate   of http://sweet.jpl.nasa.gov/2.3/reprSciUnits.owl#perMil
missing   prefix link | http://sweet.jpl.nasa.gov/2.3/reprSciUnits.owl#kilogram | should   probably be linked to the prefix
missing   property | http://sweet.jpl.nasa.gov/2.3/reprSciUnits.owl#kilogram | probably   missing property hasBaseUnit
missing   property | http://sweet.jpl.nasa.gov/2.3/reprSciUnits.owl#micro | missing   property hasSymbol
wrong   assignment | http://sweet.jpl.nasa.gov/2.3/reprSciUnits.owl#FTU | should   probably not be the same as http://sweet.jpl.nasa.gov/2.3/reprSciUnits.owl#FNU
wrong   conversion | http://sweet.jpl.nasa.gov/2.3/reprSciUnits.owl#degreeC | offset   should be exact (273,15)
wrong   conversion | http://sweet.jpl.nasa.gov/2.3/reprSciUnits.owl#degreeF | factor   and offset for other direction of conversion used
wrong   conversion | http://sweet.jpl.nasa.gov/2.3/reprSciUnits.owl#degrees | factor   for other direction of conversion used
general |   | invalid   file, see https://www.w3.org/RDF/Validator/rdfval?URI=http%3A%2F%2Fsweet.jpl.nasa.gov%2F2.3%2FreprSciUnits.owl
general |   | namespaces   are ambiguous named (e.g. http://sweet.jpl.nasa.gov/2.3/relaSci.owl#    <=> relaSci \| screla2 & http://sweet.jpl.nasa.gov/2.3/relaSci.owl   (without '#'!) <=> screla )
general |   | many   namespaces without '#', which is not usable in SPARQL

**Comment by lewismc** [comment]
Some more information on this one...

From Jen Martin Keil
==================
The comprehensive comparison results can be found on https://github.com/fusion-jena/unit-ontology-review-results .

The list of missing relations in particular can be found in file https://github.com/fusion-jena/unit-ontology-review-results/blob/master/3700%20statistic%20-%20relation%20coverage%20missing.json .
In this file you find a JSON object structured as follows:

first level is the ontology (e.g. "SWEET")
second level is the affected concept (field of application, kind of quantity, unit of measurement, prefix)
third level is the list of relation types (e.g. "prefixUnit" is the relation between a prefix and a unit)
the actual values contain the individuals of the concept without this type of relation
Please note that this files contains results for SWEET 2.3. The queries used to extract the data can be found on https://github.com/fusion-jena/unit-ontology-review/tree/master/data/SWEET/sparql .

Something we noted while starting to analyses version 3: It seems that about 40 units got lost during the conversion from .owl to .ttl of reprSciUnits.owl . The other files, however, still make use of these units.
The list of issues as found can be seen in the able above. On a first look the namespace related issues seem to be fixed in version 3.

**Comment by lewismc** [comment]
@dr-shorthair @carueda I am looking into the following right now
> Something we noted while starting to analyses version 3: It seems that about 40 units got lost during the conversion from .owl to .ttl of reprSciUnits.owl . The other files, however, still make use of these units.

**Comment by lewismc** [comment]
The top picture represents Protege 5.0.0 understanding of SWEET 2.3.0 in OWL serialization
![screen shot 2017-10-25 at 4 52 20 pm](https://user-images.githubusercontent.com/1165719/32028914-fee6766a-b9a5-11e7-827c-18106fbbce2b.png)
The bottom picture represents Protege 5.0.0 understanding of SWEET 3.0.0 in TTL serialization.
![screen shot 2017-10-25 at 4 58 31 pm](https://user-images.githubusercontent.com/1165719/32028915-fef84566-b9a5-11e7-936d-89c9333f7efc.png)
It would appear that the [rdf2rdf](http://www.l3s.de/%7Eminack/rdf2rdf/) transformation software [used to undertake the mapping]() has screwed us... it's my own fault I should have undertaken a more thorough quality assurance task post transformation.

**Comment by lewismc** [comment]
The source of the issues above was fixed in https://github.com/ESIPFed/sweet/pull/16, the only issue is that https://github.com/ESIPFed/sweet/pull/16 was fixed after https://github.com/ESIPFed/sweet/pull/37 hence the mapping seems to have failed to complete successfully.

**Comment by lewismc** [comment]
After fixing #16 again in a fresh version of SWEEt 2.3, Protege 5.0.0 now indicates
![screen shot 2017-10-25 at 5 26 39 pm](https://user-images.githubusercontent.com/1165719/32029485-c22cda8a-b9a9-11e7-9b09-82ac0c92db40.png)

**Comment by graybeal** [comment]
No fault-finding needed nor appropriate—I am confident in the work because I know you want to see it through.  

In this case, hopefully most of thse differences can be unpacked using some simple dumb search/sort/diff tricks, because the content is extremely patterned. That would be much easier than analyzing the source of each type of discrepancy.

Or, it might just be there's a file missing. :-)

**Comment by lewismc** [comment]
@graybeal , thanks, but all the same it is annoying I didn't catch this!
I am working on a fix

**Comment by brandonnodnarb** [comment]
I suggest splitting this into two issues (good catch @lewismc).  One issue being the technical one @lewismc is digging into, the other being mapping to, or otherwise re-using (I guess that would be importing) something like QUDT?

The second one likely involves further discussion, but it may be beneficial in the long run.

**Comment by dr-shorthair** [comment]
@brandonnodnarb I think you are proposing to add a new issue as part of #23 

SInce SWEET 3.0 was intended to have content equivalent to SWEET 2.3 (just in a new ns) this re-instatement needs to happen anyway.

**Comment by brandonnodnarb** [comment]
Yes, @dr-shorthair, that is correct.  I'll create a new issue.

**Comment by carueda** [comment]
@lewismc @dr-shorthair 
>... I am looking into the following right now
> 
> > Something we noted while starting to analyses version 3: It seems that about 40 units got lost during the conversion from .owl to .ttl of reprSciUnits.owl . The other files, however, still make use of these units.

So, the resolution to #58 (PR https://github.com/ESIPFed/sweet/pull/61) should include a fix for this as well.

**Comment by lewismc** [comment]
This was addressed with the release of 3.1.0
