### ISSUE TITLE
Fix un-used namespace prefixes

### ISSUE THREAD

**Issue by dr-shorthair** [ESIPFed/sweet#58]
Many many many of the namespace prefixes in almost all of the source files are bound to URI without a "/" on the end, so these prefix declarations are often just so noise.
Need to go through the source files systematically to ensure that the prefixes are bound to valid URI stems with a "/" (or "#") on the end.

e.g. the first two lines of https://github.com/ESIPFed/sweet/blob/master/human.ttl show

`@prefix human: <http://sweetontology.net/human> .`
`@prefix know: <http://sweetontology.net/repr> .`

These are not valid URI stems - no / or # on the end - so are not actually used in the rest of the file (or anywhere else). Should be 

`@prefix human: <http://sweetontology.net/human/> .`
`@prefix know: <http://sweetontology.net/repr/> .`

Note `/` on the end.

Almost all the SWEET source files have similar errors. 

(New issue spawned from #48 )

**Comment by carueda** [comment]
@lewismc  I think you created the initial ttl versions including these prefixes, so can you take this one?  I'm assuming you could use whatever tool you used before and perhaps more quickly take care of the needed fixes?

**Comment by carueda** [comment]
@dr-shorthair The hash-to-slash conversion (#48) did a systematic replacement based on a regex looking for the `#` character.  It seems the wrong prefixes are in all the TTL files not initially having such trailing hash `#`.

**Comment by lewismc** [comment]
Hi folks, please take some of this conversation over to https://github.com/ESIPFed/sweet/issues/55, i think there are some regressions when the OWL --> TTL transformation was executed and committed to master.

**Comment by dr-shorthair** [comment]
@carueda they wouldn't have worked either. I think this might explain some confusing behaviour I saw in the past, with previous versions of sweet I mean. Probably got tangled up in the rdf/XML serialization where rdf:ID automatically interpolates the #. Easy to get confused here as it's all tangled up with the rather sorry history of xml vs. rdf conception of "namespace". In rdf it is just a URI shortening trick.

**Comment by carueda** [comment]
> they wouldn't have worked either.

@dr-shorthair Not sure I follow this. 

But I agree with you about the potential confusion regarding the rdf:ID mechanism in combination with the xml:base. Anyway, again, the hash-to-slash conversion was done on the turtle serialization, not on the rdf/xml one. In other words, hashes were somehow lost during the rdf/xml-to-turtle conversion.

**Comment by dr-shorthair** [comment]
>> they wouldn't have worked either.
> @dr-shorthair Not sure I follow this.

What I mean is that the declaration `@prefix human: <http://sweetontology.net/human> .` would not result in the prefix `human:` actually appearing anywhere in the Turtle file. So though syntactically OK would have no effect. In fact the main effect has been that I see things like 
![image](https://user-images.githubusercontent.com/608303/32034191-e3342d74-ba5c-11e7-975d-52c2f6f82982.png) in TopBraid - i.e. a load of full 'namespaces' instead of their (incorrectly defined) prefixes. 

rdf2rdf may be the culprit here, but I suspect it would be easier to fix with a global replacement of 

^(\@prefix \w+: \<http://sweetontology.net/\w+)(\> \.)$

with 

$1/$2 

The prefixes won't get used until the next time you load it into an eidtor and then save, but at least we'll be on track.

**Comment by carueda** [comment]
> What I mean is that the declaration `@prefix human: <http://sweetontology.net/human> .` would not result in the prefix human: actually appearing anywhere in the Turtle file.

Yes, agree.  The problem, again, arose from the initial rdf/xml-to-turtle translation having missed those trailing hashes. Also, I have to admit, the subsequent hash-to-slash conversion could have been done a bit more intelligently, that is, at least having detected this inconsistency before actually proceeding with the conversion.

Anyways, do you think @dr-shorthair that a systematic (regex-based) conversion to include a trailing slash in all those malformed prefix lines will be a safe fix to this issue?

**Comment by carueda** [comment]
@dr-shorthair @lewismc I just applied your suggested replacement, PR https://github.com/ESIPFed/sweet/pull/61
