### ISSUE TITLE
Prettier turtle serialization regarding blank nodes

### ISSUE THREAD

**Issue by carueda** [ESIPFed/sweet#62]
As a sort of #45 follow-up, the idea here is to re-process the files so blank nodes are shown with the `[ ... ]` syntax.

For example, this in reprSciUnits.ttl:

```ttl
units:LogarithmicUnit a owl:Class ;
	rdfs:subClassOf units:Unit , _:node1btb0r2nbx1 .

_:node1btb0r2nbx1 a owl:Restriction ;
	owl:onProperty mrela:hasScale ;
	owl:allValuesFrom repr:LogarithmicScale .
```

would be converted to:

```ttl
units:LogarithmicUnit
        a                owl:Class ;
        rdfs:subClassOf  units:Unit ;
        rdfs:subClassOf  [ a                  owl:Restriction ;
                           owl:allValuesFrom  repr:LogarithmicScale ;
                           owl:onProperty     mrela:hasScale
                         ] .
```

@dr-shorthair @lewismc Your comments?  As mentioned in #45, Jena is able to generate this and I can write a script to perform this conversion.

**Comment by lewismc** [comment]
+1

**Comment by dr-shorthair** [comment]
OWL-API output is widely used in the Ontology engineering community already, probably because of the Protege link. Its not what I use, but I think we should follow the masses.  

Ideally we would configure our GitHub with post-commit hooks to process any valid RDF serialization into OWL-API Turtle, to support easy diffing.

**Comment by carueda** [comment]
Just submitted two PRs:
-  https://github.com/ESIPFed/sweet/pull/65  - Jena conversion
- https://github.com/ESIPFed/sweet/pull/66 - OWL-API conversion

Please proceed as you deem appropriate.

The code for these conversions is in this [gist](https://gist.github.com/carueda/b032f85b5d80660f2158e55ca2e8b1ab).

**Comment by carueda** [comment]
@dr-shorthair @lewismc 
I have updated the two PRs so the resulting files retain the original defined prefixes.

Again, those PRs are mainly for comparison purposes. Per Simon's comment, it seems we will proceed with the OWL-API output.  The [conversion script](https://gist.github.com/carueda/b032f85b5d80660f2158e55ca2e8b1ab) is ready to be re-run whenever convenient, especially if there are any other ongoing changes to the files that should be merged first.

**Comment by carueda** [comment]
So, let's just focus on the OWL-API one.  (just closed https://github.com/ESIPFed/sweet/pull/65).

**Comment by carueda** [comment]
Fixed with merged PR https://github.com/ESIPFed/sweet/pull/68
