### ISSUE TITLE
Coordination with ENVO?

### ISSUE THREAD

**Issue by pbuttigieg** [ESIPFed/sweet#7]
Greetings SWEET developers,

It's great to see SWEET on GitHub and moving ahead!

Over in the world of federated [ontologies for biological and biomedical applications](http://www.obofoundry.org/), the  [Environment Ontology](https://github.com/EnvironmentOntology/envo/) has been steadily growing to contextualise an ever-diversifying range of sampling and observation activities. 

We started mapping ENVO classes to SWEET back in [2012/2013](http://doi.org/10.1186/2041-1480-4-43), recognising the domain overlap of these resources. As [ENVO's scope broadens](http://doi.org/10.1186/s13326-016-0097-6) with our user community, this overlap is likely to grow, and the risk of duplication working against interoperability begins to loom.

We'd really like to synchronise our efforts with SWEET's further development under ESIP, perhaps acting as a bridge between the realm of biological/biomedical semantics and Earth systems semantics? I think there's a great opportunity here to exchange expertise and best practices while cross-linking the communities we interface with. Such a synchronisation would be timely, as we're about to refactor ENVO for increased robustness and we could align during this process. 

Please let me know if you wish to proceed with this. Until then, happy developing!

**Comment by lewismc** [comment]
@pbuttigieg yes yes yes yes yes :)
We have our monthly [ESIP Semantic Technologies](http://wiki.esipfed.org/index.php/Semantic_Technologies) meeting on the 4th Tuesday of every month at 4PM Eastern. It would be very much appreciated it you could attend and we could discuss. Thank you for reaching out it makes perfect sense.

**Comment by pbuttigieg** [comment]
@lewismc, great! That's [April 25th 16:00 Eastern / 22:00](https://www.worldtimebuddy.com/?qm=1&lid=5,2944388&h=2944388&date=2017-4-25&sln=22-23) right? I'll be there!

**Comment by lewismc** [comment]
Yes thats right. I'll ping you before the meeting. Thanks again.

**Comment by lewismc** [comment]
@rduerr this is related to your proposed ESIP Session

**Comment by rduerr** [comment]
@lewismc @pbuttigieg Great!  I decided I'd better submit the session proposal since I didn't see a relevant one on the agenda; but I would be happy to co-chair with both or either of you or ???

**Comment by lewismc** [comment]
Yes please @rduerr please let me know what kind of assistance I can provide. I invited @pbuttigieg to join us at the Telecon so it would be good to hash out some ideas then. Thank you @rduerr

**Comment by pbuttigieg** [comment]
> @lewismc @pbuttigieg Great! I decided I'd better submit the session proposal since I didn't see a relevant one on the agenda; but I would be happy to co-chair with both or either of you or ???

Yes, I'd be very happy to contribute to the session. As @lewismc noted, we can clarify things at the telecon unless there's greater urgency.

**Comment by rduerr** [comment]
OK, I am adding you two as co-convenes!  - Ruth

**Comment by lewismc** [comment]
@pbuttigieg apologies I forgot to ping you earlier. We are having our meeting today at the following 
```
 Meetings:

    Monthly Telecon
        4th Tuesday of each month at 4pm Eastern
        GoToMeeting: https://www.gotomeeting.com/join/976796333
        Phone Access: United States: +1 (872) 240-3212
        Access Code: 976-796-333 
    ESIP Meetings 

Contact Chair:

    Beth Huffer, Chair, beth@lingualogica.net 

```

**Comment by pbuttigieg** [comment]
@lewismc thanks! I'll be online at 22:00 CEST / 16:00 EDT

**Comment by dr-shorthair** [comment]
Where are the notes from that call? 
Not listed here: http://wiki.esipfed.org/index.php/Semantic_Web_Telecons :-(

**Comment by akthom** [comment]
@dr-shorthair sorry for that, notes have been in google doc here: https://docs.google.com/document/d/1vdHTXbp1G6wiwdyrC0Uw9IKgTgJF4G6vjThR2eNJ-q8/edit?usp=sharing

will be transferring to ESIP wiki once I find my login to the ESIP wiki :)

**Comment by rduerr** [comment]
Pier and I met at a hackathon a week or so ago and came up with a game plan for moving at least the cryospheric parts of SWEET and ENVO more together (mostly under #33).

**Comment by dr-shorthair** [comment]
Related to #23

**Comment by lewismc** [comment]
I'm going to resolve this issue as ENVO and SWEET coordination is an establishing _thing_ and is ongoing.
