### ISSUE TITLE
Move ontology files to subdirectory

### ISSUE THREAD

**Issue by carueda** [ESIPFed/sweet#71]
@lewismc @dr-shorthair 

This is simply a proposal to move the ontology files to a subdirectory (`src/`?) so the first level of this repository gets a bit less cluttered while also making it easier to see the contents of the README file upon a casual visit to https://github.com/ESIPFed/sweet .

**Comment by graybeal** [comment]
Like this idea. It also makes it easier to see exactly what the ontology files are, they won't be mixed in with any other files.

**Comment by rduerr** [comment]
Exactly!  Agreed...

**Comment by dr-shorthair** [comment]
+1 down with clutter!

**Comment by carueda** [comment]
Thanks all for the positive reactions.

@lewismc If you also agree, please confirm that `etc/` would be a good place (I see some stuff in there so better make sure there's no interference with other efforts) or indicate the name for the new subdirectory.

BTW here's some TODOs related with this change:

- [ ] (Carlos) Update the ["watchdog"](https://github.com/ESIPFed/sweet-tools/tree/master/sc/watchdog) script to retrieve the files for automatic COR/sweetontology updates
- [ ] (?) Any other dependent scripts/harvesters out there that the team is aware of?
- [ ] (?, Lewis) Send a note to relevant lists before proceeding with this change effect?

**Comment by lewismc** [comment]
Hi @carueda I went ahead and inacted the cleanup. All of the material previously located within ```src``` relates to the CI build I am working on. This material has been relocated to ```ci``` and all of the ontology files are now located in ```src```. This looks much cleaner.
Can you go ahead and resolve your assigned TODO above and then resolve this issue? Thank you

**Comment by carueda** [comment]
Cool, thanks @lewismc
