### ISSUE TITLE
Malformed subject URIs for owl:NameIndividuals that begin with a numeric

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/sweet#76]
**what is wrong**
The owl:NamedIndividual URIs for terms that start with a numeric value (seen in the comment preceding the defining triples) is missing the numeric value in the defining triples

**Example**
<pre>
###  http://sweetontology.net/stateTime/1day
stime:day rdf:type owl:NamedIndividual ,
                   time:Duration ;
          screla:hasUnit units:day ;
          screla:hasNumericValue "1.0"^^xsd:double .
</pre>
Should this be:
<pre>
###  http://sweetontology.net/stateTime/1day
stime:1day rdf:type owl:NamedIndividual ,
                   time:Duration ;
          screla:hasUnit units:day ;
          screla:hasNumericValue "1.0"^^xsd:double .
</pre>

**Code Affected**
https://github.com/ESIPFed/sweet/blob/a59aaa1dc5833d88b2dd4eec65b0dc1f2358c2f0/src/stateTime.ttl#L212-L290

**Comment by lewismc** [comment]
Dynamite catch @ashepherd are you able to provide a PR?

**Comment by ashepherd** [comment]
Thank you for looking into this! 
I just noticed this same issue happens at https://github.com/ESIPFed/sweet/blob/a59aaa1dc5833d88b2dd4eec65b0dc1f2358c2f0/src/stateTimeGeologic.ttl#L28-L1441 for the NamedIndividuals with triples using 
<pre>
trela:hasEndTime ptime:MYA ;
trela:hasStartTime ptime:MYA ;
</pre>

where I think ptime:MYA is missing a numeric value preceding 'MYA'

code affected:
https://github.com/ESIPFed/sweet/blob/a59aaa1dc5833d88b2dd4eec65b0dc1f2358c2f0/src/stateTimeGeologic.ttl#L1455-L2210

**Comment by ashepherd** [comment]
@lewismc I'd be happy to issue a pull request for 
https://github.com/ESIPFed/sweet/blob/a59aaa1dc5833d88b2dd4eec65b0dc1f2358c2f0/src/stateTime.ttl#L212-L290

**Comment by ashepherd** [comment]
@lewismc, I can issue a PR for the owl:NamedIndividual statements in stateTimeGeologic, but I don't have the domain knowledge to fix the trela:hasEndTime ptime:MYA ; trela:hasStartTime ptime:MYA ;

**Comment by lewismc** [comment]
Damn... @carueda could this have anything to do with the [sweet-tools](https://github.com/ESIPFed/sweet-tools/tree/master/sc) output? This seemed to be OK in SWEET 2.3
https://github.com/ESIPFed/sweet/blob/v2.3.0/2.3/stateTimeGeologic.owl

**Comment by carueda** [comment]
Yes, it seems those leading numeric characters in term identifiers were removed during the "prettification" ed4b900b564ef0cef5681009861606f067cbbbdd (#62). This was done using OWLAPI, basically by just loading the ontologies using OWLAPI and then generating the output again in Turtle format. Wondering if this has to do with malformed (local) identifiers when starting with numeric characters.  Will take a closer look when time permits.

**Comment by dr-shorthair** [comment]
You might also compare with https://www.w3.org/2006/time which defines the following: 
   :TemporalUnit rdfs:subClassOf :TemporalDuration . 
and the following instances
  :unitSecond
  :unitMinute
  :unitHour
  :unitDay
  :unitWeek
  :unitMonth
  :unitYear
which are therefore functionally equivalent to exactly 1 of each of these. 
and provides various options to define a duration
