### ISSUE TITLE
Re-run SWEET to ENVO alignment

### ISSUE THREAD

**Issue by rduerr** [ESIPFed/sweet#79]
Need to re-run the alignment between SWEET and ENVO so that I can look at the cryospheric alignments.  I'd like this run by the end of the month.``

**Comment by lewismc** [comment]
Sorry @rduerr this got los t in my TODO's, I sent an update alignment at https://github.com/cmungall/sweet-obo-alignment/pull/2
Once this is merged and closed, it will be available at https://github.com/cmungall/sweet-obo-alignment/blob/master/align-sweet-obo-envo.tsv

**Comment by rduerr** [comment]
Discovered that it has been regenerated!  So closing.... Note: I will be working through the alignments for the cryosphere starting basically now.

**Comment by lewismc** [comment]
Thank you @rduerr
