### ISSUE TITLE
updates to the ContributingGuidelines document

### ISSUE THREAD

**Issue by smrgeoinfo** [ESIPFed/sweet#90]
Clarify instructions, add information for Github Desktop users.

**Comment by lewismc** [comment]
Thanks @smrgeoinfo addressed in #91

**Comment by donnadf** [comment]
Hi,
Newbie question:
If I am interested in contributing to SWEET (at the mineral level), is
there a specific process to follow, etc.

Thank-you
Donna Fritzsche
Knowledge Architect

**Comment by lewismc** [comment]
Hi @donnadf please see https://github.com/ESIPFed/sweet/blob/master/CONTRIBUTING.md
Welcome :)
