### ISSUE TITLE
problem axiom: AquaticEcosystem SubClassOf hasRealm some Ocean

### ISSUE THREAD

**Issue by cmungall** [ESIPFed/sweet#94]
The semantics of OWL dictate that this means every instance of AquaticEcosystem bears a hasRealm relationship to some instance of Ocean. But this is not true: aquatic ecosystems can be freshwater

**Comment by dr-shorthair** [comment]
Then 
```
###  http://sweetontology.net/realmBiolBiome/MarineEcosystem
biome:MarineEcosystem rdf:type owl:Class ;
                       rdfs:subClassOf biome:AquaticEcosystem ,
                                       [ rdf:type owl:Restriction ;
                                         owl:onProperty rela:hasRealm ;
                                         owl:allValuesFrom planet:Ocean
                                       ] .
```

**Comment by lewismc** [comment]
ack @dr-shorthair 

> Marine ecosystems are among the largest of Earth's aquatic ecosystems. Examples include salt marshes, intertidal zones, estuaries, lagoons, mangroves, coral reefs, the deep sea, and the sea floor. They can be contrasted with freshwater ecosystems, which have a lower salt content.

**Comment by lewismc** [comment]
https://en.wikipedia.org/wiki/Marine_ecosystem

**Comment by smrgeoinfo** [comment]
I agree. Its a tricky topic, but in order for SWEET to be useful for any kind of inferencing, more logically coherent definitions will be required.  It might be most useful to focus on definitions for the parts of SWEET where there are some property value or subclass constraints that have logical implications.

**Comment by cmungall** [comment]
First apologies for my mistake in titling the ticket: as @lewismc points out this is a universal (aka only) restriction (allValuesFrom) rather than existential (aka some) restriction (someValuesFrom). The difference is important, but in this case there is still a problem.

I think yamz would be great for crowdsourcing some definitions for ocean, but regardless of this, a single counter-example of a an aquatic ecosystem that has a non-ocean realm is sufficient to disprove the axiom. For example if we agree that the [Okavango_Delta](https://en.wikipedia.org/wiki/Okavango_Delta) is an aquatic ecosystem, and that is has at least one realm, and that realm is not an ocean then it disproves the axiom.

To resolve this I might suggest using a more general class than 'ocean', such as 'water body' (in ENVO, we might represent this as 'aquatic biome' is determined-by some 'water body'.. but I note we are lacking any axiomatization on aquatic biome, cc @pbuttigieg). 

I agree with @smrgeoinfo that it would be good to add more logical definitions. A good place to start is on some of the ObjectProperty definitions, and just coming up with some textual elucidations of hasRealm and friends (cc @diatomsRCool)
